In [1]:
import numpy as np

In [13]:
a = np.array([1,2,3])
b = np.array([[1,2,3], [4,5,6]])
c = np.ones((2,3))
d = np.zeros((3,1))
e = np.full((3,3), 5)
f = np.random.random((2,3))

In [14]:
print(a)
print(a.shape)
print(a[0], a[1], a[2])

[1 2 3]
(3,)
1 2 3


In [15]:
print(b)
print(b.shape)
print(b[0, 0], b[0][0])

[[1 2 3]
 [4 5 6]]
(2, 3)
1 1


In [16]:
print(c)
print(d)
print(e)
print(f)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0.]
 [0.]
 [0.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[0.26004355 0.77019344 0.59319943]
 [0.10702098 0.38267963 0.57240143]]


In [19]:
g = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

h = g[:2, 1:3]

print(g)
print(h)
h[0,0]=100
print(g)
print(h)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
[[  1 100   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   3]
 [  6   7]]


In [21]:
x = np.array([[1,2], [3,4]], dtype=np.float32)
y = np.array([[1,2], [3,4]], dtype=np.float32)
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x.dot(y))

[[2. 4.]
 [6. 8.]]
[[0. 0.]
 [0. 0.]]
[[ 1.  4.]
 [ 9. 16.]]
[[1. 1.]
 [1. 1.]]
[[ 7. 10.]
 [15. 22.]]
